# Generated by Django 3.2.3 on 2021-06-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(default='email', max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(default='last-name', max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='password1',
            field=models.CharField(default='password', max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='password2',
            field=models.CharField(default='password', max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_name',
            field=models.CharField(default='user-name', max_length=200),
        ),
    ]
